version: "3.2"

services:
  controller:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 controller/run.py
    container_name: controller
    volumes:
      - .:/app
    ports:
      - 9090:9090
    environment: 
      REDIS_HOST: redis
    
  controller_periodic_task:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 controller/periodic_task.py
    volumes:
      - .:/app
    environment: 
      REDIS_HOST: redis
      MANIPULATOR_HOST: manipulator

  sensor:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python3 sensor/sensor.py  
    environment:
      RPS: 300
      CONTROLLER_HOST: controller
    volumes:
      - .:/app
 
  manipulator:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 manipulator/manipulator.py 
    container_name: manipulator
    ports:
      - 9099:9099
    volumes:
      - .:/app

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./local/redis-data:/var/lib/redis

