version: "3.2"
services:

 controller:
    build:
        context: ./
        dockerfile: ./docker/Dockerfile.controller
    volumes:
        - .:/app
    ports:
      - "9090:9090"

 sensor:
    build: 
        context: ./
        dockerfile: ./docker/Dockerfile.sensor

    environment:
        - RPS=300
    volumes:
        - .:/app
 
 manipulator:
    build:
        context: ./
        dockerfile: ./docker/Dockerfile.manipulator
    volumes:
        - .:/app
    ports:
      - "9099:9099"

 redis:
    image: "redis:alpine"

    command: redis-server

    ports:
     - "6379:6379"

    volumes:
     - $PWD/redis-data:/var/lib/redis

    environment:
     - REDIS_REPLICATION_MODE=master
